### PR TITLE
Client

### PR DESCRIPTION
**Pull request by ahmeddelattarr**

### CODE REVIEW

**Comment by ahmeddelattarr** [comment]
#25

**Comment by ahmeddelattarr** [comment]
**TODO** 

- [x] Add endpoint to see the user likes.
- [x] Add endpoint to see the user replies.
- [ ] Create a Profile model and serializer to make a profile page with bio, social accounts, and an image.
- [ ] post tags (optional)

**Comment by 0marAmara** [comment]
Todo
Add the pagination
Add the username as a field for comments

**Comment by ahmeddelattarr** [comment]
Todo : order the posts from the newest to the oldest

**Comment by ahmeddelattarr** [comment]
programming-or-googling
i added one line and it works correctly now

**Comment by ahmeddelattarr** [comment]
LGTM!
good job @0marAmara

**Pull request merged**
